rango_app/urls.py
"""Defines urls for rango_app"""
from django.urls import path
from . import views

app_name = "rango_app"
urlpatterns = [
    path(
        'register_profile/', 
        views.register_profile, 
        name='register_profile'
    ),
    path(
        "", 
        views.index, 
        name='index',
    ),
    path(
        'about/', 
        views.about, 
        name='about',
    ),
    path(
        'category/<slug:category_name_slug>/', 
        views.show_category, 
        name='show_category',
    ),
    path(
        'add_category/', 
        views.add_category, 
        name='add_category',
    ),
    path(
        'category/<slug:category_name_slug>/add_page/', 
        views.add_page, 
        name='add_page',
    ),
    path(
        'restricted/',
        views.restricted,
        name='restricted'
    ),
    path(
        'goto/', 
        views.track_url, 
        name='goto'
    ),
    path(
        'search/',
        views.search_page,
        name='search_page'
    ),
    path(
        'profile/<username>/', 
        views.ProfileView.as_view(), 
        name='profile'),
    path(
        'profile/', 
        views.ListProfilesView.as_view(), 
        name='list_profiles'
    ),
    path(
        'like/',
        views.like_category,
        name='like_category'
    ),
    path(
        'suggest/',
        views.suggest_category,
        name='suggest_category'
    ),
    
]

tango_rango/urls.py
from django.contrib import admin
from django.urls import path, reverse, include
from django.conf import settings
from django.conf.urls.static import static
from registration.backends.simple.views import RegistrationView

class MyRegistrationView(RegistrationView):
    def get_success_url(self, user):
        return reverse('rango_app:register_profile')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('rango_app.urls')),
    path(
        'accounts/register/', 
        MyRegistrationView.as_view(),
        name='registration_register'
        ),

    path('accounts/', include('registration.backends.simple.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rango_app/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class Page(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)
    message = models.TextField(blank=True)

    def __str__(self):
        return self.user.username

rango_app/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Page, Category, UserProfile

class CategoryForm(forms.ModelForm):
    name = forms.CharField(
            max_length=128,
            help_text="Please enter category name."
        )
    views = forms.IntegerField(
            widget=forms.HiddenInput(), 
            initial=0
        )
    likes = forms.IntegerField(
            widget=forms.HiddenInput(),
            initial=0
        )
    slug = forms.CharField(
            widget=forms.HiddenInput(),
            required=False
        )

    class Meta:
        model = Category
        fields = ('name',)

class PageForm(forms.ModelForm):
    title = forms.CharField(
            max_length=128,
            help_text="Please enter title for the page:"
        )
    url = forms.URLField(
            max_length=200,
            help_text="Please enter the page url:"
        )
    views = forms.IntegerField(
            widget=forms.HiddenInput(),
            initial=0
        )
    class Meta:
        model = Page
        exclude = ('category',)
     # Cleaning data.    
    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')
        if url and not url.startswith('https://'):
            url = 'https://' + url
            cleaned_data['url'] = url

            return cleaned_data

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password',)

class UserProfileForm(forms.ModelForm):
    website = forms.URLField(required=False)
    picture = forms.ImageField(required=False)
    message = forms.CharField(widget=forms.Textarea(
        attrs={'cols':25, 'rows': 15}), 
        required=False)

    class Meta:
        model = UserProfile
        fields = ('website', 'picture', 'message',)

rango_app/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from .models import Category, Page, UserProfile
from .forms import CategoryForm, PageForm, UserForm, UserProfileForm
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from datetime import datetime
from django.contrib.auth.models import User
from rango_app.templatetags.rango_app_template_tags import get_category_list
from django.views import View
from django.utils.decorators import method_decorator

def index(request):
    """The Home Page for Rango"""
    category_list = Category.objects.order_by("-likes")[:6]
    page_list = Page.objects.order_by("-views")[:6]
    context_dict = {'categories': category_list, 'pages': page_list}

    visitor_cookie_handler(request)
    context_dict['visits'] = request.session['visits']
    response = render(request,'rango_app/index.html',context=context_dict)
    return response

def show_category(request, category_name_slug):
    """Navigate to each category"""
    context_dict = {}
    try:
        category = Category.objects.get(slug=category_name_slug)
        pages = Page.objects.filter(category=category).order_by('-views')
        context_dict['pages'] = pages
        context_dict['category'] = category
    except Category.DoesNotExist:
        context_dict['category'] = None
        context_dict['pages'] = None

    return render(request, 'rango_app/category.html', context_dict)

@login_required
def add_category(request):
    """Allowing adding new categories"""
    form = CategoryForm

    if request.method == 'POST':
        form = CategoryForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return index(request)
        else:
            print(form.errors)

    return render(request, 'rango_app/add_category.html', {'form': form})

@login_required
def add_page(request, category_name_slug):
    """Allow adding pages to existing categories"""
    try:
        category = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        category = None

    form = PageForm()
    if request.method == "POST":
        form = PageForm(request.POST)
        if form.is_valid():
            if category:
                page = form.save(commit=False)
                page.category = category
                page.views = 0
                page.save()
                return show_category(request, category_name_slug)
        else:
            print(form.errors)

    context_dict = {'form': form, 'category': category}
    return render(request, 'rango_app/add_page.html', context_dict)

def about(request):
    """The About Page for Rango"""
    return render(request, 'rango_app/about.html', {})


@login_required
def restricted(request):
    message = f"Welcome {request.user.username.title()}! "
    message += f"You can view this content because you are logged in."
    message += f"\nYou can always leave me feedback or express concerns"
    message += f" at francomania23@live.com. Enjoy!"
    message += f"\nSpecial regards, FrankOlum."
    context_dict = {'message': message}
    return render(request, 'rango_app/restricted.html', context_dict)

# Define a helper function client cookies
def get_server_side_cookie(request, cookie, default_val=None):
    val = request.session.get(cookie)
    if not val:
        val = default_val
    return val

def visitor_cookie_handler(request):
    visits = int(get_server_side_cookie(request,'visits','1'))

    last_visit_cookie = get_server_side_cookie(
            request, 'last_visit', str(datetime.now())
        )
    last_visit_time =datetime.strptime(
            last_visit_cookie[:-7], '%Y-%m-%d %H:%M:%S'
        )
    if (datetime.now()-last_visit_time).days > 0:
        visits += 1
        request.session['last_visit'] = str(datetime.now())
    else:
        visits = 1
        request.session['last_visit'] = last_visit_cookie
    request.session['visits'] = visits

def search_page(request):
    search_text = request.GET['query']
    pages = Page.objects.filter(title__contains=search_text)
    context_dict = {'pages': pages}
    return render(request, 'rango_app/search.html', context_dict)

def track_url(request):
    page_id = None
    url = '/'
    if request.method == "GET":
        if 'page_id' in request.GET:
            page_id = request.GET['page_id']
            if page_id:
                page = Page.objects.get(id=page_id)
                page.views += 1
                page.save()
                url = page.url
            else:
                pass

    return redirect(url)

@login_required
def register_profile(request):
    form = UserProfileForm()
    
    if request.method == 'POST':
        form = UserProfileForm(request.POST, request.FILES)
        
        if form.is_valid():
            user_profile = form.save(commit=False)
            user_profile.user = request.user
            user_profile.save()
            
            return redirect("/")
        else:
            print(form.errors)
    
    context_dict = {'form': form}
    return render(request, 'rango_app/profile_registration.html', context_dict)

# Using Class-Based View
class ProfileView(View):
    def get_user_details(self, username):
        try:
            user = User.objects.get(username=username)
        except User.DoesNotExist:
            return None
        
        user_profile = UserProfile.objects.get_or_create(user=user)[0]
        form = UserProfileForm({'website': user_profile.website,
                                'picture': user_profile.picture,
                                'message': user_profile.message})
        
        return (user, user_profile, form)
    
    @method_decorator(login_required)
    def get(self, request, username):
        try:
            (user, user_profile, form) = self.get_user_details(username)
        except TypeError:
            return redirect("/")
        
        context_dict = {'user_profile': user_profile,
                        'selected_user': user,
                        'form': form}
        
        return render(request, 'rango_app/profile.html', context_dict)
    
    @method_decorator(login_required)
    def post(self, request, username):
        try:
            (user, user_profile, form) = self.get_user_details(username)
        except TypeError:
            return redirect("/")
        
        form = UserProfileForm(request.POST, request.FILES, instance=user_profile)
        
        if form.is_valid():
            form.save(commit=True)
            return redirect("/")
        else:
            print(form.errors)
        
        context_dict = {'user_profile': user_profile,
                        'selected_user': user,
                        'form': form}
        
        return render(request, 'rango_app/profile.html', context_dict)
        
            
class ListProfilesView(View):
    @method_decorator(login_required)
    def get(self, request):
        profiles = UserProfile.objects.all()
        
        return render(request,
                      'rango_app/list_profiles.html',
                      {'userprofile_list': profiles})

@login_required
def like_category(request):
    cat_id = None
    if request.method == 'GET':
        cat_id = request.GET.get('category_id')
        likes=0
        if cat_id:
            cat = Category.objects.get(id=int(cat_id))
            if cat:
                likes = cat.likes + 1
                cat.likes = likes
                cat.save()
    return HttpResponse(likes)

def suggest_category(request):
    cat_list= []
    starts_with = ''
    if request.method == 'GET':
        starts_with = request.GET['suggestion']
    cat_list = get_category_list(7, starts_with)
    return render(request, 'rango_app/cats.html', {'cats': cat_list})

templates/rango_app/about.html
{% extends 'rango_app/base.html' %}
{% load static %}

{% block title_block %}
    About
{% endblock %}

{% block body_block %}
    <div class="container">
    <h1 class="display-3"><strong>About Rango</strong></h1>
    <p class="lead">Rango book-marking site is a unique app that offers pages 
    embedded in various categories ranging from: fashion, lifestyle, cuisines, 
    blockbusters, and favourite delicacies. Hence the alias, Rango Page House!
    At Rango, you are free to browse, view, and like any categories and pages of 
    your choice.</p><p class="lead">
    Please sign up for an account, upload a profile photo if you so choose, 
    and get started adding pages and categories!</p>
    <p><i>Copyright - ©frankolum2021. All Rights Reserved.</i></p>
    <div>
        <img class="rangoimage" src ="{% static 'images/rangoone.png' %}"
        alt="picture of rango">
    </div>
</div>   
{% endblock %}

templates/rango_app/add_category.html
{% extends 'rango_app/base.html' %}
{% load static %}
{% block title_block %}
    Add Category
{% endblock %}
{% load bootstrap4 %}
{% block body_block %}
  <div class="container">
  <h2 class="form-heading">Add a Category</h2>
  <div>
      <form 
        id="Category_form" 
        method="post" 
        action="{% url 'rango_app:add_category' %}">
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
              {{ hidden }}
            {% endfor %}
            {% for field in form.visible_fields %}
              {{ field.errors }}
              {{ field.help_text }}
              {{ field }}
            {% endfor %}
        {% buttons %}
        <input 
        type="submit" 
        name="submit" 
        value="Create Category" 
        class="btn btn-primary" />
        {% endbuttons %}
      </form>
  </div>
</div>
{% endblock %}
   

templates/rango_app/add_page.html
{% extends 'rango_app/base.html' %}
{% load static %}
{% block title_block %}
    Add Page
{% endblock %}
{% load bootstrap4 %}
{% block body_block %}
    <div class="container">
    {% if category %}
    <h2 class="form-heading">Add Page to {{ category.name }}</h2>
    <form id="Page_form" 
    method="POST" 
    action="{% url 'rango_app:add_page' category.slug %}">
    {% csrf_token %}
    {% for hidden in form.hidden_fields %}
        {{ hidden }}
    {% endfor %}
    {% for field in form.visible_fields %}
        {{ field.errors }}
        {{ field.help_text }}
        {{ field }}
    {% endfor %}
    {% buttons %}
    <input type="submit" name="submit" value="Add Page" class="btn btn-primary">
    {% endbuttons %}        
    </form>
    {% else %}
    Category by this name doesn't exist!
    {% endif %}
</div>
{% endblock %}

templates/rango_app/base.html
<!DOCTYPE html>
{% load static %}
{% load rango_app_template_tags %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, 
        shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'favicon.ico' %}">  
    <title>
        Rango -
        {% block title_block %}
        {% endblock %}
    </title>
    {% load bootstrap4 %}
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
    <style type="text/css">
        .sidenav{
                float: right; width:15%; font-style:italic;
                margin: 0px 20px 0px 0px; padding: 5px;
                border-top: 1px solid red; border-bottom: 1px solid red;
                height:370px; overflow-x: hidden;
            }
        .rangoimage{
                 float: left; width: 70%; margin-left:6px;
                 height: 320px;
            }
        .tdecorate{
                text-decoration: underline; font-style:oblique;
                color: darkBlue;
            }
        .mydisplay{
                color: red; font-weight: bold;
            }
        .picformat{
                margin: 0px 0px 10px 30px; float:left; width:25%;
            }
        .indent{
                margin: 2px 0px 0px 5px;
            }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4 border">

    <li class="navbar-brand"><strong>Rango Page House</strong></li>

    <button class="navbar-toggler" type="button" data-toggle="collapse"
        data-target="#navbarCollapse" aria-controls="navbarCollapse"
        aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'rango_app:index' %}">Home</a>
        </li>
        <li>
          <a class="nav-link" href="{% url 'rango_app:about' %}">About</a>
        </li>
        <li class="indent">
          <form class="form" action="{% url 'rango_app:search_page' %}" 
            method="get">
            {% csrf_token %}
            <input type="text" size="20" name="query" 
                placeholder="search page...">
            <button type="submit" 
              class="btn btn-sm btn-primary">Get Result</button>
          </form>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
    {% if user.is_authenticated %}
    <li class="nav-item">
        <a class="nav-link" 
        href="{% url 'rango_app:profile' user.username %}">Your Profile</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" 
        href="{% url 'rango_app:list_profiles' %}">List Profiles</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'rango_app:restricted' %}">
          Restricted
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'rango_app:add_category' %}">
            Add New Category
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'auth_logout' %}">Logout</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'auth_password_change' %}?next='auth_password_change_done' ">Change Password</a>
    </li>
    {% else %}
    <li class="nav-item">
        <a class="nav-link" 
        href="{% url 'registration_register' %}">Register here</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'auth_login' %}">Login</a>
    </li>
    {% endif %}
    </ul>
    </div>
    </nav>
    <div>
      {% block body_block %}{% endblock%}
    </div>
    <div class="sidenav">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-pills flex-column">
            <li class="nav-item">Get Category!</li>
              <form>
              <li class="nav-item"><input class="search-query form-control" 
                type="text"
                name="suggestion" value="" id="suggestion" />
              </li>
            </form>
          </ul>
            <hr />
    <div id="cats">
    </div>
        </div>
      </div>
    </div>
    <script src="{% static 'js/rango-ajax.js' %}"></script>
    <script src="{% static 'js/rango-jquery.js' %}"></script>    
</body>
</html>

templates/rango_app/category.html
{% extends 'rango_app/base.html' %}
{% load static %}

{% block title_block %}
   {{ category.name }}
{% endblock %}
   
{% block body_block %}
    <div class="container">
    {% if category %}
      <h1>{{ category.name }}</h1>
      <div>
        <strong id="like_count">{{ category.likes }}</strong>
        people like this category
      {% if user.is_authenticated %}
      <button id="likes" class="btn btn-sm btn-primary" 
        data-catid="{{category.id}}" type="button" >
        Like
      </button>
      {% endif %}
      </div>
      {% if pages %}
        <ul>
        {% for page in pages %}
          <li><a href="{% url 'rango_app:goto' %}?page_id={{page.id}}">
          {{ page.title }}</a>
          {% if page.views > 1 %}
              ({{page.views}} views)
          {% elif page.views == 1 %}
              ({{page.views}} view)
          {% endif %}
          </li>
        {% endfor %}
        </ul>
      {% else %}
        <strong>No pages currently in category</strong>
      {% endif %}
      <a href="{% url 'rango_app:add_page' category.slug %}">Add a Page</a>
    {% else %}
     The specified category does not exist!
    {% endif %}
    </div>
{% endblock %}
    
    

templates/rango_app/cats.html
<ul class="nav nav-pills flex-column">
{% if cats %}
    {% for c in cats %}
        {% if c == act_cat %}
            <li>
                <strong>
                <a href="{% url 'rango_app:show_category' c.slug  %}">
                    {{ c.name }}
                </a>
                </strong>
            </li>
        {% else %}
            <li>
                <a href="{% url 'rango_app:show_category' c.slug %}">
                    {{ c.name }}
                </a>
            </li>
        {% endif %}
    {% endfor %} 
{% else %}
    <li><strong>There are no categories present.</strong></li>
{% endif %}   
</ul>

templates/rango_app/index.html
{% extends 'rango_app/base.html' %}
{% load static %}

{% block title_block %}
     Index 
{% endblock %}

{% block body_block %}
<div class="container">
  <div class="jumbotron">
  <h1 class="display-3 mydisplay">"Rango Book-Marking Site...</h1>
  {% if user.is_authenticated %}
    <h1>how's the going {{ user.username }}!"</h1>
    {% else %}
    <h1>how's the going partner!"</h1>
    {% endif %}
    <p>You have visited this site on {{ visits }} occassion(s).</p>
</div>
<div class="row marketing">
  <div class="col-lg-6">
    <h4 class="tdecorate">Most Liked Categories</h4>
    <span class="check">⭐⭐⭐⭐⭐</span>
    <p>
      {% if categories %}
      <ul>
        {% for category in categories %}
        <li><a href="{% url 'rango_app:show_category' category.slug %}">
          {{ category.name }}
        </a></li>
        {% endfor %}
      </ul>
        {% else %}
          <strong>There are no categories present.</strong>
        {% endif %}
    </p>
  </div>
  <div class="col-lg-6">
    <h4 class="tdecorate">Most Viewed Pages</h4>
    <span class="recheck">⭐⭐⭐⭐⭐</span>
    <p>
      {% if pages %}
    <ul>
      {% for page in pages %}
      <li><a href="{{ page.url }}">{{ page.title }}</a></li>
      {% endfor %}
    </ul>
      {% else %}
      <strong>There are no pages available.</strong>
      {% endif %}
    </p>
  </div>
</div>
</div>
<img src="{% static 'images/rango5.jpg' %}" class="rangoimage" alt="Picture of Rango">
{% endblock %}

templates/rango_app/list_profiles.html
{% extends 'rango_app/base.html' %}
{% load static %}

{% block title_block %}User Profiles{% endblock %}

{% block body_block %}
<div class="container">
<h1 class="display-3">User Profiles</h1>

<div class="panel">
    {% if userprofile_list %}
    <div class="panel-heading">
        <!-- Display search results in an ordered list -->
        <div class="panel-body">
            <div class="list-group">
                {% for listuser in userprofile_list %}
                <div class="list-group-item">
                    {% if listuser.picture %}
                    <img width="64" height="64" 
                    src="{{ MEDIA_URL}}{{listuser.picture}}"/>
                    {% else %}
                    <img src="https://via.placeholder.com/64x64.png?text=IMAGE">
                    {% endif %}
                    <h4 class="list-group-item-heading">
                    <a href=
                    "https://pagehouse.herokuapp.com/profile/{{listuser.user.username}}/">
                    {{ listuser.user.username }}</a>
                    </h4>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    {% else %}
        <p>There are no users for the site.</p>
    {% endif %}
</div>
</div>
{% endblock %}

templates/rango_app/profile.html
{% extends 'rango_app/base.html' %}
{% load static %}  
{% block title_block %}
    Profile for {{ selected_user.username }}
{% endblock %}
{% load bootstrap4 %}
    {% block body_block %}
    <div class="jumbotron p-4">
        <div class="container">
            <h1 class="jumbotron-heading">{{ selected_user.username }}'s Profile</h1>
        </div>
    </div>
    
    <div class="container">
        <div class="row">
            <img src="{{ MEDIA_URL }}{{ user_profile.picture }}"
                 width="300"
                 height="300"
                 alt="{{ selected_user.username }}'s profile image" />
            <br />
            <div>
                {% if selected_user == user %}
                <form method="post" action="." enctype="multipart/form-data">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    {% buttons %}
                    <input type="submit" value="Update" class="btn btn-primary"/>
                    {% endbuttons %}
                </form>
                {% else %}
                <p>
                    <strong>Website:</strong>
                    <a href="{{ user_profile.website }}">{{ user_profile.website }}</a>
                </p>
                <p>
                    <strong>Message:</strong>
                    <a href="{{ user_profile.message }}">{{ user_profile.message }}</a>
                </p>
                {% endif %}
            </div>
        </div>
    </div>
    {% endblock %}

templates/rango_app/profile_registration.html
{% extends 'rango_app/base.html' %}
{% load static %}   
    {% block title_block %}
        Create a profile
    {% endblock %}
{% load bootstrap4 %}
    {% block body_block %}
    <div class="jumbotron p-4">
        <div class="container">
            <h1 class="jumbotron-heading">Create a profile on the go!</h1>
        </div>
    </div>
    
    <div class="container">
        <div class="row">
            <form method="post"
                  action="{% url 'rango_app:register_profile' %}"
                  enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                {% buttons %}
                <input type="submit" class="btn btn-primary" 
                    value="Create Profile" />
                {% endbuttons %}
            </form>
        </div>
    </div>
    {% endblock %}

templates/rango_app/restricted.html
{% extends 'rango_app/base.html' %}
{% load static %}
{% block title_block %}
{% endblock %}

{% block body_block %}
<div class="container">
<h1 class="display-3">Restricted Page</h1>
    <p class="lead"><i>{{ message }}</i></p>
</div>
{% endblock %}

templates/rango_app/search.html
{% extends 'rango_app/base.html' %}
{% load static %}
{% block title_block %}
    search
{% endblock %}
{% load bootstrap4 %}
{% block body_block %}
<div class="container">
<h1>Search Results</h1>
{% if pages %}
    <ul>
        {% for page in pages %}
        <li><a href="{% url 'rango_app:goto' %}?page_id={{page.id}}">
            {{ page.title }}</a>
            {% if page.views > 1 %}
              ({{page.views}} views)
            {% elif page.views == 1 %}
              ({{page.views}} view)
            {% endif %}
        </li>
        {% endfor %}
    </ul>
        {% else %}
        <strong>Page requested is not available</strong>
{% endif %}
</div>
{% endblock %}